- name: Ensure keyring directory exists
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download Jenkins GPG key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.gpg
    mode: '0644'
  become: yes

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/"
    state: present
  become: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present
  become: yes

