---
- name: Ensure prerequisites for Docker are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: yes

- name: Remove old Docker keyring if exists
  file:
    path: /usr/share/keyrings/docker-archive-keyring.gpg
    state: absent
  become: yes
  ignore_errors: yes

- name: Remove old Docker repository files
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent
  become: yes
  ignore_errors: yes

- name: Add Docker official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
  become: yes

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

